# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'RandomSoju' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RandomSoju

pod 'NMapsMap'
pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'

end
